apiVersion: v1
kind: Service
metadata:
  name: petclinic-api-service
  namespace: petclinic-ns
spec:
  type: LoadBalancer
  selector:
    app: petclinic-api
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP

